CREATE TABLE [dbo].[Chore]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[Status] NVARCHAR(20) NOT NULL DEFAULT 'ToDo',
	[FamilyID] INT NOT NULL FOREIGN KEY REFERENCES Family(ID),
	[AssignedToUserID] INT NULL FOREIGN KEY REFERENCES [User](ID)
)
