CREATE TABLE [dbo].[Event]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[StartTime] DATETIME NOT NULL,
	[EndTime] DATETIME NOT NULL,
	[FamilyID] INT NOT NULL FOREIGN KEY REFERENCES Family(ID)
)
